#!/usr/bin/env bash

### Instructions:
### $ cp .env_example .env
### $ cp .secrets_example .secrets
### Customize the .env file
### Customize the .secrets file
### $ ./build

export $(grep -v '^#' .env | xargs)

docker build --rm \
    --tag $MCS_IMAGE_NAME \
    --build-arg VERSION=$VERSION \
    --build-arg DEV=$DEV \
    --build-arg MCS_REPO=$MCS_REPO \
    --build-arg MCS_BASEURL=$MCS_BASEURL \
    --build-arg CMAPI_REPO=$CMAPI_REPO \
    --build-arg CMAPI_BASEURL=$CMAPI_BASEURL \
    --build-arg SPIDER=$SPIDER .

if [[ $USE_COMPOSE == true ]]; then
    if [[ $MAXSCALE == true ]]; then
    docker compose -f docker-compose-mxs.yml up -d
    docker exec -it $PM1 provision
    else
    docker compose -f docker-compose.yml up -d
    docker exec -it $PM1 provision
    fi
else
    docker run -d --name $PM1 --hostname $PM1 --env PM1=$PM1 --shm-size=512mb $MCS_IMAGE_NAME
    docker exec -it $PM1 provision
fi
