#!/usr/bin/env bash

### Instructions:
### $ cp .env_example .env
### $ cp .secrets_example .secrets
### Customize the .env file
### Customize the .secrets file
### $ ./build

export $(grep -v '^#' .env | xargs)

docker build --rm \
    --tag $MCS_IMAGE_NAME \
    --build-arg VERSION=$VERSION \
    --build-arg DEV=$DEV \
    --build-arg MCS_REPO=$MCS_REPO \
    --build-arg MCS_BASEURL=$MCS_BASEURL \
    --build-arg CMAPI_REPO=$CMAPI_REPO \
    --build-arg CMAPI_BASEURL=$CMAPI_BASEURL \
    --build-arg SPIDER=$SPIDER .
