#!/usr/bin/env bash
# shellcheck disable=SC2046
# Columnstore Team Use Only

export $(grep -v '^#' .env | xargs)

if [[ $(docker ps -a -q) ]]; then
    docker stop $(docker ps -a -q)
fi

docker system prune -a --volumes --force

if [[ $(docker buildx ls | grep columnstore) ]]; then
    docker buildx stop $BUILDX_CONTAINER
    docker buildx rm $BUILDX_CONTAINER --force
fi

docker buildx prune --all --force
