#!/usr/bin/env bash
# Columnstore Team Use Only

export $(grep -v '^#' .env | xargs)

docker stop $(docker ps -a -q)

docker system prune -a --volumes --force

docker build --rm \
    --tag $MCS_IMAGE_NAME \
    --build-arg VERSION=$VERSION \
    --build-arg TOKEN=$TOKEN \
    --build-arg DEV=$DEV \
    --build-arg MCS_REPO=$MCS_REPO \
    --build-arg MCS_BASEURL=$MCS_BASEURL \
    --build-arg CMAPI_REPO=$CMAPI_REPO \
    --build-arg CMAPI_BASEURL=$CMAPI_BASEURL .

if [[ $CLUSTER == true ]]; then
    docker-compose -f docker-compose-full.yml up -d
    docker exec -it $PM1 provision-full
else
    docker run -d --name $PM1 --hostname $PM1 --env PM1=$PM1 --shm-size=512mb $MCS_IMAGE_NAME
    docker exec -it $PM1 provision
fi
