#!/usr/bin/env bash
# Columnstore Team Use Only

### Instructions:
### $ cp .secrets_example .secrets
### Customize the .secrets file
### $ ./rebuild

export $(grep -v '^#' .env | xargs)

docker stop $(docker ps -a -q)

docker system prune -a --volumes --force

docker build --rm \
    --tag $MCS_IMAGE_NAME \
    --build-arg VERSION=$VERSION \
    --build-arg DEV=$DEV \
    --build-arg MCS_REPO=$MCS_REPO \
    --build-arg MCS_BASEURL=$MCS_BASEURL \
    --build-arg CMAPI_REPO=$CMAPI_REPO \
    --build-arg CMAPI_BASEURL=$CMAPI_BASEURL .

if [[ $CLUSTER == true ]]; then
    if [[ $MAXSCALE == true ]]; then
    docker compose -f docker-compose-mxs.yml up -d
    docker exec -it $PM1 provision-mxs
    else
    docker compose -f docker-compose.yml up -d
    docker exec -it $PM1 provision
    fi
else
    docker run -d --name $PM1 --hostname $PM1 --env PM1=$PM1 --shm-size=512mb $MCS_IMAGE_NAME
    docker exec -it $PM1 provision
fi
