#!/usr/bin/env bash
# shellcheck disable=SC2046
# Columnstore Team Use Only

export $(grep -v '^#' .env | xargs)

docker stop $(docker ps -a -q)

docker system prune -a --volumes --force

docker build --rm \
    --tag $MCS_IMAGE_NAME \
    --build-arg VERSION=$VERSION \
    --build-arg TOKEN=$TOKEN \
    --build-arg DEV=$DEV \
    --build-arg MCSBRANCH=$MCSBRANCH \
    --build-arg MCSBUILDPATH=$MCSBUILDPATH \
    --build-arg CMAPIBRANCH=$CMAPIBRANCH \
    --build-arg CMAPIBUILDPATH=$CMAPIBUILDPATH .

if [ $CLUSTER == true ]; then
    docker-compose up -d
    docker exec -it $PM1 provision
else
    docker run -d --name $PM1 --hostname $PM1 --env PM1=$PM1 --shm-size=512mb $MCS_IMAGE_NAME
    docker exec -it $PM1 provision
fi
