#!/usr/bin/env bash
# shellcheck disable=SC2046
# Columnstore Team Use Only

export $(grep -v '^#' .env | xargs)

docker-compose down

docker volume prune -f

if [ $CLUSTER == true ]; then
    docker-compose up -d
    docker exec -it $PM1 provision
else
    docker run -d --name $PM1 --hostname $PM1 --env PM1=$PM1 --shm-size=512mb $MCS_IMAGE_NAME
    docker exec -it $PM1 provision
fi
