#!/usr/bin/env bash

export $(grep -v '^#' .env | xargs)

if [[ $CLUSTER == true ]]; then
    if [[ $MAXSCALE == true ]]; then
    docker-compose -f docker-compose-mxs.yml up -d
    docker exec -it $PM1 provision-mxs
    else
    docker compose -f docker-compose.yml up -d
    docker exec -it $PM1 provision
    fi
else
    docker run -d --name $PM1 --hostname $PM1 --env PM1=$PM1 --shm-size=512mb $MCS_IMAGE_NAME
    docker exec -it $PM1 provision
fi
