#!/usr/bin/env bash
# Columnstore Team Use Only
# shellcheck source=/dev/null

source .env

USE_COMPOSE=${USE_COMPOSE:-false}
MAXSCALE=${MAXSCALE:-false}
PM1=${PM1:-mcs1}

if [[ "${USE_COMPOSE}" == true ]]; then
    if [[ "${MAXSCALE}" == true ]]; then
        docker compose -f docker-compose-mxs.yml down
    else
        docker compose -f docker-compose.yml down
    fi
else
    docker stop "${PM1}"
fi
