#!/usr/bin/env bash
# Columnstore Team Use Only
# shellcheck source=/dev/null
#
# Example:
#   ./stop_project
#   ./stop_project clean
#   ./stop_project clean all

source .env

USE_COMPOSE=${USE_COMPOSE:-false}
MAXSCALE=${MAXSCALE:-false}
PM1=${PM1:-mcs1}

if [[ "${USE_COMPOSE}" == true ]]; then
    if [[ "${MAXSCALE}" == true ]]; then
        docker compose -f docker-compose-mxs.yml down
    else
        docker compose -f docker-compose.yml down
    fi
else
    docker stop "${PM1}"
fi

if [ ! -z $1 ] && [ $1 == "clean" ]; then
    
    BUILDX_CONTAINER=${BUILDX_CONTAINER:-columnstore}
    MCS_IMAGE_NAME=${MCS_IMAGE_NAME:-mariadb/columnstore}

    echo "[-] Deleting containers w/image: $MCS_IMAGE_NAME"
    CONTAINER_IDS=$(docker ps -a -q --filter "ancestor=$MCS_IMAGE_NAME")
    if [[ ! -z $CONTAINER_IDS ]]; then
        docker rm $CONTAINER_IDS
    fi

    echo "[-] Deleting image: $MCS_IMAGE_NAME"
    IMAGE_IDS=$(docker images -q --filter "reference=$MCS_IMAGE_NAME" )
    if [[ ! -z $IMAGE_IDS ]]; then
        docker rmi $IMAGE_IDS
    fi

    echo "[-] Deleting unused build caches"
    docker builder prune --force

    if [ ! -z $2 ] && [ $2 == "all" ]; then
        docker system prune -a --volumes --force
    fi;
fi;