#!/usr/bin/env bash
# Columnstore Team Use Only
# shellcheck source=/dev/null

source .env

USE_COMPOSE=${USE_COMPOSE:-true}
MAXSCALE=${MAXSCALE:-false}
PM1=${PM1:-mcs1}
PM2=${PM2:-mcs2}
PM3=${PM3:-mcs3}
MCS_IMAGE_NAME=${MCS_IMAGE_NAME:-mariadb/columnstore}
USE_S3_STORAGE=${USE_S3_STORAGE:-false}
S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-myaccesskey}
S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-mysecretkey}
S3_BUCKET=${S3_BUCKET:-mybucket}
S3_ENDPOINT=${S3_ENDPOINT:-s3.us-west-2.amazonaws.com}
S3_REGION=${S3_REGION:-us-west-2}

docker compose -f docker-compose-mxs.yml down
docker volume prune