#!/usr/bin/bash

# Set Variables
IFLAG=/etc/columnstore/container-initialized
LOG_PREFIX=/var/log/mariadb/columnstore
MCS_INSTALL_BIN=/usr/bin
API_KEY="${API_KEY:-somekey123}"

# Intialize Container If Necessary
if [ ! -e $IFLAG ]; then
  $MCS_INSTALL_BIN/columnstore-init &> $LOG_PREFIX/columnstore-init.log
fi

# Start cmapi
echo Starting...

touch $LOG_PREFIX/cmapi_server.log && chmod 666 $LOG_PREFIX/cmapi_server.log
cd /opt/cmapi
PYTHONPATH=/opt/cmapi/deps /opt/cmapi/python/bin/python3 -m cmapi_server &> $LOG_PREFIX/cmapi_server.log &
echo CMAPI PID = $!

# Start MariaDB
/usr/share/mysql/mysql.server start

# Start Columnstore Engine Proceses For Single Node
if [[ $(hostname -s) == $PM1 ]]; then
  curl -s -X PUT "https://$PM1:8640/cmapi/0.4.0/cluster/add-node" --header 'Content-Type:application/json' --header "x-api-key:$API_KEY" --data '{"timeout":60, "node": "'$PM1'"}' -k
fi

exit 0
