#!/usr/bin/bash

# Set Variables
IFLAG=/etc/columnstore/container-initialized
LOG_PREFIX=/var/log/mariadb/columnstore
MCS_INSTALL_BIN=/usr/bin
API_KEY=${API_KEY:-somekey123}

# Intialize Container If Necessary
if [ ! -e $IFLAG ]; then
  cp /opt/cmapi/engine_files/mcs-loadbrm.py /usr/bin/mcs-loadbrm.py
  $MCS_INSTALL_BIN/columnstore-init &> $LOG_PREFIX/columnstore-init.log
fi

# Start cmapi
echo Starting...

touch $LOG_PREFIX/cmapi_server.log && chmod 666 $LOG_PREFIX/cmapi_server.log
cd /opt/cmapi
PYTHONPATH=/opt/cmapi/deps /opt/cmapi/python/bin/python3 -m cmapi_server &> $LOG_PREFIX/cmapi_server.log &
echo CMAPI PID = $!

# Start MariaDB
/usr/share/mysql/mysql.server start

exit 0
