#!/bin/bash

# Set Variables
CMAPI_PID=$(pgrep -f cmapi_server)

# Stop System
echo 'Stopping Cluster Manager API...'

/etc/init.d/mariadb stop

if [[ ! -z $CMAPI_PID ]]; then
    kill $CMAPI_PID > /dev/null
fi
