#!/usr/bin/bash

# Set Variables
CMAPI_PID=$(pgrep -f cmapi_server)

# Stop System
echo Stopping...

/usr/share/mysql/mysql.server stop

if [[ ! -z $CMAPI_PID ]]; then
  kill $CMAPI_PID > /dev/null
fi
