#!/bin/bash

# Set Variables
CMAPI_PID=$(pgrep -f cmapi_server)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}***** Shutting Down ColumnStore System *****${NC}"

# Stop Columnstore

if mcs cluster stop  > /dev/null 2>&1; then
    echo -e "Stopping ColumnStore Cluster... ${GREEN}done${NC}"
else
    echo -e "Stopping ColumnStore Cluster... ${RED}fail${NC}"
    exit 1
fi

# Stop CMAPI
if [[ -n ${CMAPI_PID} ]]; then
    if kill "${CMAPI_PID}" > /dev/null; then
        echo -e "Stopping Cluster Manager API... ${GREEN}done${NC}"
    else
        echo -e "Stopping Cluster Manager API... ${RED}fail${NC}"
        exit 1
    fi
fi

# Stop MariaDB
if mariadb-admin ping > /dev/null 2>&1; then
    if mariadb-admin shutdown > /dev/null 2>&1; then
        echo -e "Stopping MariaDB Server... ${GREEN}done${NC}"
    else
        echo -e "Stopping MariaDB Server... ${RED}fail${NC}"
        exit 1
    fi
fi