#!/usr/bin/env bash

# Set Some Variables
COLXML='/etc/columnstore/Columnstore.xml'
IFLAG='/etc/columnstore/container-initialized'
PFLAG='/etc/columnstore/container-provisioned'
LOG_PREFIX='/var/log/mariadb/columnstore'
MCS_INSTALL_BIN='/usr/bin'
CMAPI_KEY="${CMAPI_KEY:-somekey123}"
SKYSQL_INITIALIZATION="${SKYSQL_INITIALIZATION:-0}"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Intialize Container If Necessary
if [[ ! -e ${IFLAG} ]]; then
    if ! "${MCS_INSTALL_BIN}"/columnstore-init &> "${LOG_PREFIX}"/columnstore-init.log; then
        echo "ERROR: During Initialization."
        exit 1
    fi
fi

# Dynamic Memory Allocation
if [[ "${SKYSQL_INITIALIZATION}" == 1 ]]; then
    TOTALUMMEMORY="22%"
    NUMBLOCKSPCT="45"
    xmlstarlet ed -L -u '/Columnstore/HashJoin/TotalUmMemory' -v "${TOTALUMMEMORY}" "${COLXML}"
    xmlstarlet ed -L -u '/Columnstore/DBBC/NumBlocksPct' -v "${NUMBLOCKSPCT}" "${COLXML}"
fi

# Start CMAPI
touch "${LOG_PREFIX}"/cmapi_server.log && chmod 666 "${LOG_PREFIX}"/cmapi_server.log
cd /usr/share/columnstore/cmapi || exit
if PYTHONPATH=/usr/share/columnstore/cmapi/deps /usr/share/columnstore/cmapi/python/bin/python3 -m cmapi_server &> /dev/null &
then
    echo -e "Starting Cluster Manager API... ${GREEN}done${NC}"
else
    echo -e "Starting Cluster Manager API... ${RED}fail${NC}"
    exit 1
fi

# Start Columnstore
if [[ -e ${PFLAG} ]]; then
    if mcs cluster start &> /dev/null; then
        echo -e "Starting ColumnStore Cluster... ${GREEN}done${NC}"
    else
        echo -e "Starting ColumnStore Cluster... ${RED}fail${NC}"
        exit 1
    fi
fi

# Start MariaDB
mariadb-admin ping &> /dev/null
if ! mariadb-admin ping &> /dev/null; then
    if mariadbd-safe &> /dev/null &
    then
        echo -e "Starting MariaDB Server... ${GREEN}done${NC}"
    else
        echo -e "Starting MariaDB Server... ${RED}fail${NC}"
        exit 1
    fi
    sleep 5
fi

exit 0
