#!/usr/bin/env bash

# Set Some Variables
COLXML='/etc/columnstore/Columnstore.xml'
IFLAG='/etc/columnstore/container-initialized'
LOG_PREFIX='/var/log/mariadb/columnstore'
MCS_INSTALL_BIN='/usr/bin'
CMAPI_KEY="${CMAPI_KEY:-somekey123}"
TOTALUMMEMORY="${TOTALUMMEMORY:-25%}"
NUMBLOCKSPCT="${NUMBLOCKPCT:-50}"
SKYSQL_INITIALIZATION="${SKYSQL_INITIALIZATION:-0}"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Dynamic Memory Allocation
if [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ] && [ "$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)" -le "$(free -b | awk 'NR==2{printf "%d", $2 }')" ]; then
    # If limited by cgroups (e.g. in SkySQL)
    MAX_RAM_BYTES=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
    MAX_RAM=$((MAX_RAM_BYTES/1024/1024))
    TOTALUMMEMORY=$( echo $MAX_RAM / 4  | bc )M
    NUMBLOCKSPCT=$( echo $MAX_RAM / 2  | bc )M
fi

# Performance Tuning
xmlstarlet ed -L -u '/Columnstore/HashJoin/TotalUmMemory' -v "$TOTALUMMEMORY" $COLXML
xmlstarlet ed -L -u '/Columnstore/DBBC/NumBlocksPct' -v "$NUMBLOCKSPCT" $COLXML

# Start CMAPI
touch $LOG_PREFIX/cmapi_server.log && chmod 666 $LOG_PREFIX/cmapi_server.log
cd /usr/share/columnstore/cmapi || exit
PYTHONPATH=/usr/share/columnstore/cmapi/deps /usr/share/columnstore/cmapi/python/bin/python3 -m cmapi_server &> $LOG_PREFIX/cmapi_server.log &
if [[ $? -eq 0 ]]; then
    printf "Starting Cluster Manager API... ${GREEN}done${NC}\n"
else
    printf "Starting Cluster Manager API... ${RED}fail${NC}\n"
    exit 1
fi

# Intialize Container If Necessary
if [ ! -e $IFLAG ]; then
    $MCS_INSTALL_BIN/columnstore-init &> $LOG_PREFIX/columnstore-init.log
    if [ $? -ne 0 ]; then
        echo "ERROR: During Initialization."
        exit 1
    fi
fi

# Start MariaDB & Columnstore
mariadb-admin ping > /dev/null 2>&1
if [[ $? -ne 0 ]]; then
    mariadbd-safe  > /dev/null 2>&1 &
    if [[ $? -eq 0 ]]; then
        printf "Starting MariaDB Server... ${GREEN}done${NC}\n"
    else
        printf "Starting MariaDB Server... ${RED}fail${NC}\n"
        exit 1
    fi
    sleep 5
fi

exit 0
