#!/bin/bash

# Set Variables
CMAPI_PID=$(pgrep -f cmapi_server)

# Stop System
echo 'Stopping Cluster Manager API...'
mcs cluster stop > /dev/null 2>&1

if [[ ! -z $CMAPI_PID ]]; then
    kill $CMAPI_PID > /dev/null
fi
