#!/usr/bin/env bash

TOKEN=
source /tmp/.secrets
curl -LsS https://dlm.mariadb.com/enterprise-release-helpers/mariadb_es_repo_setup | bash -s -- --mariadb-server-version="$1" --token="${TOKEN}" --apply